# Generated by Django 4.2.28 on 2026-03-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
