# Generated by Django 4.2.28 on 2026-04-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reporte_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='creada_por',
        ),
        migrations.AddField(
            model_name='categoria',
            name='creada_por_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_creadas_admin', to='usuarios.admin'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creada_por_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_creadas_profesor', to='usuarios.profesor'),
        ),
    ]
